[package]
name = "crusty"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
rpassword = "7"
ssh2 = "0.9"
zeroize = { version = "1.6", features = ["derive"] }
shell-escape = "0.1"
